### ISSUE TITLE
Theme breaks in slash command pop-up

### ISSUE THREAD

**Issue by sharunkumar** [datsfilipe/better-discord#1]
![image](https://user-images.githubusercontent.com/715417/140198927-07982d45-5ce0-4a3f-8cf9-a36d6f88b4d7.png)

![image](https://user-images.githubusercontent.com/715417/140198940-69b87a4a-16d8-413a-8836-bff5ae822783.png)

**Comment by datsfilipe** [comment]
Thanks for the feedback, I'll fix it.

**Comment by datsfilipe** [comment]
Fixed in version 2.3.2.
